package com.github.concussionconnect.Controller;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import com.github.concussionconnect.Model.ConnectToDB;
import com.github.concussionconnect.Model.SymptomAdapter;
import com.github.concussionconnect.Model.SymptomModel;
import com.github.concussionconnect.R;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.firebase.firestore.DocumentSnapshot;

import java.util.ArrayList;
import java.util.Random;

import static android.content.ContentValues.TAG;

public class ResearchSymptomsActivity extends Activity implements View.OnClickListener{
    private ArrayList<SymptomModel> symptomList;
    private Button next;
    private ListView viewList;
    SymptomAdapter sympAdapt;
    Bundle bundle;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_research_symptoms);
        symptomList = SymptomModel.getSymptomArray(getResources().getStringArray(R.array.symptom_list));
        next = (Button) findViewById(R.id.nextButton1);
        next.setOnClickListener(this);
        viewList = (ListView) findViewById(R.id.listView2);
        sympAdapt = new SymptomAdapter(symptomList, this);
        viewList.setAdapter(sympAdapt);
        bundle = getIntent().getExtras();
    }

    @Override
    public void onClick(View v) {
        if(v == next) {

            final String adminId = createID();

            ConnectToDB.getSessionReference(adminId,
                    new OnSuccessListener<DocumentSnapshot>() {
                        @Override
                        public void onSuccess(DocumentSnapshot snap) {
                            if (snap.exists()) {
                                Toast.makeText(getApplicationContext(), "Autogenerated ID failed; try again!", Toast.LENGTH_LONG).show();
                            } else {
                                ConnectToDB.createTrainerSession(adminId, 1, 0, "dual", false,
                                        new OnSuccessListener<Void>() {
                                            @Override
                                            public void onSuccess(Void aVoid) {
                                                beginTest(adminId);
                                                //Toast.makeText(getApplicationContext(), "Your ID is " + adminId + ". Put this code into the VR App", Toast.LENGTH_LONG).show();

                                                //added
                                                LayoutInflater inflater = getLayoutInflater();
                                                View layout = inflater.inflate(R.layout.custom_toast,
                                                        (ViewGroup) findViewById(R.id.custom_toast_container));

                                                TextView text = (TextView) layout.findViewById(R.id.text);
                                                text.setText("Your ID is " + adminId + ". Put this code into the VR App");

                                                Toast toast = new Toast(getApplicationContext());
                                                toast.setGravity(Gravity.CENTER_VERTICAL, 0, 0);
                                                toast.setDuration(Toast.LENGTH_LONG);
                                                toast.setView(layout);
                                                toast.show();
                                                //end added
                                                Log.d(TAG, "Trainer session created!");
                                            }
                                        },
                                        new OnFailureListener() {
                                            @Override
                                            public void onFailure(@NonNull Exception e) {
                                                Log.w(TAG, "Error creating trainer session", e);
                                            }
                                        }
                                );
                            }
                        }
                    },
                    new OnFailureListener() {
                        @Override
                        public void onFailure(@NonNull Exception e) {
                            Log.w(TAG, "Error creating trainer session", e);
                        }
                    }
            );


        }
    }

    public void beginTest(String adminId) {
        Intent intent = new Intent(this, OpeningPageForTests.class);



        bundle.putString("ID", adminId);
        String listAnswer = "memory_word_list_" + 1;
        int id = getResources().getIdentifier(listAnswer, "array", getPackageName());
        bundle.putInt("listId", id);

        ArrayList<SymptomModel> symptoms = new ArrayList<>();
        for (SymptomModel x : sympAdapt.getSympList()) {
            symptoms.add(x);
        }

        bundle.putSerializable("symptoms", symptoms);

        intent.putExtras(bundle);
        startActivity(intent);
    }

    public String createID() {
        Random rand = new Random();
        String id = "";
        for (int i = 0; i < 6; i++) {
            int rand_int = rand.nextInt(9);
            id += rand_int;
        }
        return id;
    }

}